var listSV=[
    {
      studentId:"SV001"  ,
      studsentZName :"Nguyễn Văn A",
      age : 20,
      sex : true,
      birthDate : "2002-04-23",
      birthPlace: "HN",
      adress : "25, Vũ Ngọc Phan",
    },
    {
      studentId:"SV002"  ,
      studsentZName :"Nguyễn Văn B",
      age : 21,
      sex : false,
      birthDate : "2001-09-09",
      birthPlace: "ĐN",
      adress : "1, Ngô Quyền",
    },
    {
      studentId:"SV003"  ,
      studsentZName :"Nguyễn Văn C",
      age : 19,
      sex : true,
      birthDate : "2003-07-07",
      birthPlace: "HCM",
      adress : "1,Lý Tự Trọng",
    },
    {
        studentId:"SV004"  ,
        studsentZName :"Nguyễn Văn D",
        age : 29,
        sex : false,
        birthDate : "2005-07-07",
        birthPlace: "HCM",
        adress : "1,Lý Tự Trọng",
    },
]